name: Docker Build

on:
  pull_request:
    branches:
      - master
      - testcafe-vm # TODO: Take this out upon approval

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: saucelabs/stt-testcafe-node
          tag_with_ref: true
          cache_froms: saucelabs/stt-testcafe-node:latest
          push: false
      
      # Checkout the latest saucectl
      - uses: actions/checkout@v2
        with:
          repository: saucelabs/saucectl
          path: saucectl

      # Build saucectl
      - run: pushd saucectl && make build && popd
        name: Build Saucectl and run E2E tests

      # Run e2e tests
      # TODO: Run a saucectl test on testcafe local here
      #- run: saucectl run
        #env:
          #SKIP_CI: true
          #SAUCE_CTL_BINARY: ./saucectl/saucectl
        #name: Build Saucectl and run E2E tests
  build-ubuntu-bundle-and-test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - name: Install FFMPEG so that bundle installs without error
        run: npm install -g @ffmpeg-installer/ffmpeg
      - 
        name: Bundle Directory
        run: bash ./scripts/bundle.sh
      - 
        name: List bundle contents
        run: ls -R bundle/
  build-windows-bundle-and-test:
    runs-on: windows-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - name: Install FFMPEG so that bundle installs without error
        run: npm install -g @ffmpeg-installer/ffmpeg
      - 
        name: Bundle Directory
        run: bash ./scripts/bundle.sh
      - 
        name: List bundle contents
        run: ls -R bundle/
  build-macos-bundle-and-test:
    runs-on: macos-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - uses: FedericoCarboni/setup-ffmpeg@v1-beta
        id: setup-ffmpeg
      - 
        name: Bundle Directory
        run: bash ./scripts/bundle.sh
      - 
        name: List bundle contents
        run: ls -R bundle/
