name: Test

on:
  pull_request:
    branches:
      - main

env:
  SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
  SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
  NODE_VERSION: 16

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Unit Test
        run: npm run unit-test

      - name: Lint
        run: npm run lint

  integration:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get TestCafe Version
        run: |
          TESTCAFE_VERSION=$(< package-lock.json jq -r '.dependencies["testcafe"].version')
          echo "testcafe_version=$TESTCAFE_VERSION" >> $GITHUB_ENV

      - name: Build Docker Image
        uses: docker/build-push-action@v3
        with:
          cache-from: saucelabs/stt-testcafe-node:latest
          push: false
          load: true
          tags: saucelabs/stt-testcafe-node:local
          build-args: |
            BUILD_TAG=${{ github.ref }}
            TESTCAFE_VERSION=${{ env.testcafe_version }}

      - name: Setup saucectl
        uses: saucelabs/saucectl-run-action@v2
        with:
          skip-run: true

      - name: Run tests
        run: ./tests/run.sh
        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}

  build-windows-bundle:
    runs-on: windows-latest
    needs: [test]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Google Cloud Login
        id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCS_RUNNER_SA_KEY }}'

      - name: Install gcloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCS_RUNNER_PROJECT_ID }}
        env:
          CLOUDSDK_PYTHON: ${{env.pythonLocation}}\python.exe

      - name: Update Release version
        run: npm version --no-git-tag-version 1.0.0

      - run: npm ci --production

      - name: Setup ffmpeg
        uses: FedericoCarboni/setup-ffmpeg@v2
        if: ${{ steps.prep.outputs.asset_id == '' }}
        id: setup-ffmpeg
        with:
          token: ${{ github.token }}

      - name: Bundle Directory
        run: bash ./scripts/bundle.sh

      - name: Archive bundle
        uses: azure/powershell@v1
        with:
          inlineScript: |
            Compress-Archive bundle/ sauce-testcafe-runner.zip
          azPSVersion: '3.1.0'

      - name: Upload to GCS
        run: |
          gsutil cp ./sauce-testcafe-runner.zip gs://${{ secrets.GCS_RUNNER_BUCKET }}/sauce-testcafe-runner-${{ github.run_id }}.zip

  windows-bundle-test:
    needs: [build-windows-bundle]
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Setup saucectl
        run: npm install -g saucectl

      - name: Test on Sauce
        working-directory: ./tests/fixtures/post-release
        run: |
          saucectl run --runner-version "url: https://storage.googleapis.com/${{ secrets.GCS_RUNNER_BUCKET }}/sauce-testcafe-runner-${{ github.run_id }}.zip" --config ./.sauce/config_win.yml

  build-mac-bundle:
    runs-on: macos-latest
    needs: [test]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Google Cloud Login
        id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCS_RUNNER_SA_KEY }}'

      - name: Install gcloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCS_RUNNER_PROJECT_ID }}

      - name: Update Release version
        run: npm version --no-git-tag-version 1.0.0

      - name: Install Dependencies
        run: npm ci --production

      - uses: FedericoCarboni/setup-ffmpeg@v2
        if: ${{ steps.prep.outputs.asset_id == '' }}
        id: setup-ffmpeg
        with:
          token: ${{ github.token }}

      - name: Bundle Directory
        run: bash ./scripts/bundle.sh

      - name: Archive Bundle
        run: zip -r sauce-testcafe-macos.zip bundle/

      - name: Upload to GCS
        run: |
          gsutil cp ./sauce-testcafe-macos.zip gs://${{ secrets.GCS_RUNNER_BUCKET }}/sauce-testcafe-macos-${{ github.run_id }}.zip

  mac-bundle-test:
    runs-on: macos-latest
    needs: [build-mac-bundle]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup saucectl
        run: npm i -g saucectl

      - name: Test on Sauce
        working-directory: ./tests/fixtures/post-release
        run: |
          saucectl run --config .sauce/config_mac.yml --runner-version "url: https://storage.googleapis.com/${{ secrets.GCS_RUNNER_BUCKET }}/sauce-testcafe-macos-${{ github.run_id }}.zip"

  run-bundles-with-sauce-connect:
    runs-on: ubuntu-latest
    needs: [build-windows-bundle, build-mac-bundle]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup saucectl
        run: npm install -g saucectl

      - name: Run web-page
        run: |
          python -m http.server 8000 &
        working-directory: ./tests/integration/sauce-connect/www/

      - name: Start sauce-connect
        uses: saucelabs/sauce-connect-action@v2
        with:
          username: ${{ secrets.SAUCE_USERNAME }}
          accessKey: ${{ secrets.SAUCE_ACCESS_KEY }}
          tunnelIdentifier: github-testcafe-sc-check-tunnel
          scVersion: 4.8.1

      - name: run saucectl (Windows)
        run: |
          saucectl run --config .sauce/config.yml --select-suite "Sauce with sauce-connect (windows)" --runner-version "url: https://storage.googleapis.com/${{ secrets.GCS_RUNNER_BUCKET }}/sauce-testcafe-runner-${{ github.run_id }}.zip"
        working-directory: ./tests/integration/sauce-connect/

      - name: run saucectl (MacOS)
        run: |
          saucectl run --config .sauce/config.yml --select-suite "Sauce with sauce-connect (mac)"  --runner-version "url: https://storage.googleapis.com/${{ secrets.GCS_RUNNER_BUCKET }}/sauce-testcafe-macos-${{ github.run_id }}.zip"
        working-directory: ./tests/integration/sauce-connect/
