name: Test

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: saucelabs/stt-testcafe-node
          tag_with_ref: true
          cache_froms: saucelabs/stt-testcafe-node:latest
          push: false
          tags: local

      - uses: saucelabs/saucectl-run-action@v1
        with:
          skip-run: true

      # Run tests
      # TODO: Run a saucectl test on testcafe local here
      - name: Run tests
        run: ./tests/run.sh
        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}

  build-windows-bundle-and-test:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Use Node.js v14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install gcloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCS_RUNNER_SA_KEY }}
          project_id: ${{ secrets.GCS_RUNNER_PROJECT_ID }}
        env:
          CLOUDSDK_PYTHON: ${{env.pythonLocation}}\python.exe

      - name: Update Release version
        run: npm version --no-git-tag-version 1.0.0

      - run: npm ci --production

      - uses: FedericoCarboni/setup-ffmpeg@v1
        if: ${{ steps.prep.outputs.asset_id == '' }}
        id: setup-ffmpeg
        with:
          token: ${{ github.token }}

      - name: Bundle Directory
        run: bash ./scripts/bundle.sh

      - name: Archive bundle
        uses: azure/powershell@v1
        with:
          inlineScript: |
            Compress-Archive bundle/ sauce-testcafe-runner.zip
          azPSVersion: '3.1.0'

      - name: Upload to GCS
        run: |
          gsutil cp ./sauce-testcafe-runner.zip gs://${{ secrets.GCS_RUNNER_BUCKET }}/sauce-testcafe-runner-${{ github.run_id }}.zip

      - name: Test on Sauce
        working-directory: ./tests/fixtures/post-release
        run: |
          npx saucectl run --config .sauce/config_win.yml --runner-version "url: https://storage.googleapis.com/${{ secrets.GCS_RUNNER_BUCKET }}/sauce-testcafe-runner-${{ github.run_id }}.zip"

  build-mac-bundle-and-test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Use Node.js v14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install gcloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCS_RUNNER_SA_KEY }}
          project_id: ${{ secrets.GCS_RUNNER_PROJECT_ID }}
        env:
          CLOUDSDK_PYTHON: ${{env.pythonLocation}}\python.exe

      - name: Update Release version
        run: npm version --no-git-tag-version 1.0.0

      - run: npm ci --production

      - uses: FedericoCarboni/setup-ffmpeg@v1
        if: ${{ steps.prep.outputs.asset_id == '' }}
        id: setup-ffmpeg
        with:
          token: ${{ github.token }}

      - name: Bundle Directory
        run: bash ./scripts/bundle.sh

      - name: Archive bundle
        run: zip -r sauce-testcafe-macos.zip bundle/

      - name: Upload to GCS
        run: |
          gsutil cp ./sauce-testcafe-macos.zip gs://${{ secrets.GCS_RUNNER_BUCKET }}/sauce-testcafe-macos-${{ github.run_id }}.zip

      - name: Test on Sauce
        working-directory: ./tests/fixtures/post-release
        run: |
          npx saucectl run --config .sauce/config_mac.yml --runner-version "url: https://storage.googleapis.com/${{ secrets.GCS_RUNNER_BUCKET }}/sauce-testcafe-runner-${{ github.run_id }}.zip"
