name: Test

on:
  pull_request:
    branches:
      - master
      - testcafe-vm # TODO: Take this out upon approval

jobs:
  build:
    runs-on: ubuntu-latest
    container: golang:1.16-alpine
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          push: false
          context: .
          file: ./Dockerfile
          tags: saucelabs/stt-testcafe-node:local
          build-args: |
            BUILD_TAG=local
      
      # Checkout the latest saucectl
      - uses: actions/checkout@v2
        with:
          repository: saucelabs/saucectl
          path: saucectl
      
      - name: Install Dependencies
        run: apk add --no-cache git gcc g++ curl bash

      # Build saucectl
      - name: Build SauceCtl
        run: |
          cd saucectl
          go install ./...
          CGO_ENABLED=0 go build cmd/saucectl/saucectl.go
          GOOS=windows GOARCH=amd64 go build cmd/saucectl/saucectl.go
          cd ..

      # Run tests
      # TODO: Run a saucectl test on testcafe local here
      - name: Run tests
        run: ./tests/run.sh
        env:
          SAUCE_CTL_BINARY: ./saucectl/saucectl
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}

  # The GitHub Actions ubuntu version doesn't work because
  #   "Could not complete test. Reason 'Your Linux version does not have a graphic subsystem to run chrome with a GUI. You can launch the browser in headless mode. If you use a portable browser version, specify the browser alias before the path instead of the 'path' prefix. For more information, see https://devexpress.github.io/testcafe/documentation/guides/concepts/browsers.html#test-in-headless-mode'"
  #   Keeping this around in case we ever need to figure out how to support Linux bundles
  #build-ubuntu-bundle-and-test:
    #runs-on: ubuntu-latest
    #steps:
      #-
        #name: Checkout
        #uses: actions/checkout@v2
      #- uses: FedericoCarboni/setup-ffmpeg@v1-beta
        #id: setup-ffmpeg
      #- 
        #name: Bundle Directory
        #run: bash ./scripts/bundle.sh
      #- 
        #name: List bundle contents
        #run: ls -R bundle/
  build-windows-bundle-and-test:
    runs-on: windows-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - uses: FedericoCarboni/setup-ffmpeg@v1-beta
        id: setup-ffmpeg
      - 
        name: Bundle Directory
        run: bash ./scripts/bundle.sh
      - 
        name: List bundle contents
        run: ls -R bundle/
#  build-macos-bundle-and-test:
#    runs-on: macos-latest
#    steps:
#      -
#        name: Checkout
#        uses: actions/checkout@v2
#      - uses: FedericoCarboni/setup-ffmpeg@v1-beta
#        id: setup-ffmpeg
#      - 
#        name: Bundle Directory
#        run: bash ./scripts/bundle.sh
#      - 
#        name: List bundle contents
#        run: ls -R bundle/
